### ISSUE TITLE
"Unwrap" function still crashes Notepad++

### ISSUE THREAD

**Issue by pryrt** [rainman74/NPPTextFX2#1]
As I explained [in the Community Forum](https://community.notepad-plus-plus.org/post/78442), the TextFX "unwrap" function crashes Notepad++ v8.4-and-newer because the plugin's code uses an out-of-date interface.  This NPPTextFX2 plugin did not fix that problem, so it still crashes Notepad++ v8.4-and-newer.

**Comment by rainman74** [comment]
> As I explained [in the Community Forum](https://community.notepad-plus-plus.org/post/78442), the TextFX "unwrap" function crashes Notepad++ v8.4-and-newer because the plugin's code uses an out-of-date interface. This NPPTextFX2 plugin did not fix that problem, so it still crashes Notepad++ v8.4-and-newer.

Yes, I can confirm that. I will remove the unwrap function.

Are there any other problems?

**Comment by pryrt** [comment]
I am not actually a TextFX user, so I haven't tested all the functions.  I would highly recommend that you go through every function and make sure it works before the next version.

Also, I would probably recommend trying to _fix_ the issues, rather than just disabling the features, because if you have to disable too many of people's favorite TextFX features, they won't bother using your plugin.

**Comment by rainman74** [comment]
> I am not actually a TextFX user, so I haven't tested all the functions. I would highly recommend that you go through every function and make sure it works before the next version.
> 
> Also, I would probably recommend trying to _fix_ the issues, rather than just disabling the features, because if you have to disable too many of people's favorite TextFX features, they won't bother using your plugin.

Thank you very much for your comment. I have removed the unwrap function for now in v0.31.

I will have a look at the code when I have time. For now, I just want to make the plugin error-free and executable again with the current Notepad++ version.
