### ISSUE TITLE
TextFX Edit

### ISSUE THREAD

**Issue by Dwza** [rainman74/NPPTextFX2#11]
Its not about an issue... more an request that textFx Edit will be implemented again.
I really need it to format some textfile in kind of a table way... you know.. makingg

```
aaaa|bbb|cccccc|ddddddddddd|ee
1111111|22222222|3|444|5555555
```
to 
```
aaaa    | bbb      | cccccc | ddddddddddd | ee
1111111 | 22222222 | 3      | 444         | 5555555
```
and those files got about 400 lines and about 3 columns...
I really would love to see this feature again since i cant find anything similar.

Thank you :)

**Comment by rainman74** [comment]
> aaaa|bbb|cccccc|ddddddddddd|ee
> 1111111|22222222|3|444|5555555

The function "The Line up multiple lines" is available with the x86 plugin version and can be used with the 32 bit version of NotePad++ without errors.

You can use NotePad++ in parallel with the 64 and 32 bit portable version in a separate directory.

I have no plans to upgrade the 64 bit version in the near future, so this is my recommended approach.

**Comment by Dwza** [comment]
Ok, thank you for you fast reply and I will have a look at the portable version and will try your approach. I will return to tell if this worked :D
