### ISSUE TITLE
Reflow Comment Text

### ISSUE THREAD

**Issue by wayne-taylor** [rainman74/NPPTextFX2#12]
There are other tools that will automatically advance to the next line when typing comments, but they will not reflow text to a specific column. TextFX was suggested, then I discovered your implementation. What I could not find was a way to select a block of commented text and have it reformatted so that whole words would extend to a designated column, then <CR><LF> and continue on the next line, using a tab indent for each new paragraph.

**Comment by rainman74** [comment]
> There are other tools that will automatically advance to the next line when typing comments, but they will not reflow text to a specific column. TextFX was suggested, then I discovered your implementation. What I could not find was a way to select a block of commented text and have it reformatted so that whole words would extend to a designated column, then and continue on the next line, using a tab indent for each new paragraph.

I do not plan to integrate this feature in the foreseeable future. I'm sorry
