### ISSUE TITLE
Naming of DLL and ZIP and folder

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [rainman74/NPPTextFX2#13]
The 64-zip contains the DLL without "64", but the MD says it should be in a folder with same name. for example "NppTextFX64".
Is this correct?

**Comment by rainman74** [comment]
> Die 64-zip enthält die DLL ohne "64", aber der MD sagt, dass sie in einem Ordner mit demselben Namen sein sollte. z.B. "NppTextFX64". Stimmt das?

That was just one example. It doesn't matter how you name the DLL, only the identical folder name is important.
