### ISSUE TITLE
Compability w/ comparePlus plugin

### ISSUE THREAD

**Issue by sovalyeler** [rainman74/NPPTextFX2#14]
Thank you for this plugin. Because of your efforts I've been able to continue using this plugin.

( https://github.com/pnedev/comparePlus/issues/353 )
I've recently installed comparePlus plugin. However, after compare plugin finishes comparing, Notepad++ crashes. I found out that it's incompatible w/ TextFX2. Without TextFX2, it works fine. Can you please install comparePlus and look into it?

**Comment by rainman74** [comment]
> Thank you for this plugin. Because of your efforts I've been able to continue using this plugin.
> 
> ( [pnedev/comparePlus#353](https://github.com/pnedev/comparePlus/issues/353) ) I've recently installed comparePlus plugin. However, after compare plugin finishes comparing, Notepad++ crashes. I found out that it's incompatible w/ TextFX2. Without TextFX2, it works fine. Can you please install comparePlus and look into it?

Yes, I can confirm the behavior (tested x64 build only). But with the normal ComparePlugin there is no problem. Therefore I refrain from an error analysis in TextFX2. If this unexpectedly requires a fix in TextFX2, feel free to post a pull request.
