### ISSUE TITLE
makes NPP crash when ComparePlus also installed

### ISSUE THREAD

**Issue by pezacz** [rainman74/NPPTextFX2#16]
Steps to reproduce
-Install NPPTextFX2
-Install ComparePlus
-type few letters
-open new tab/file (CTRL+N), type few letters
-press CTRL+ALT+1
-switch to file (tab) 1
-press CTRL+ALT+C
-at this moment, both NPP64 and NPP32 should crash

**Comment by rainman74** [comment]
duplicate to https://github.com/rainman74/NPPTextFX2/issues/14
