### ISSUE TITLE
Error when using "Sort lines"

### ISSUE THREAD

**Issue by PhilCS** [rainman74/NPPTextFX2#28]
Whenever I try to use TextFX Tools -> Sort lines, I get the error "This tool is not compatible with binary text. Please select text without [NUL] characters" regardless of which file I try it with. Even a new file with only a single character will throw the error.

I am using the x64 version.

**Comment by rainman74** [comment]
> Whenever I try to use TextFX Tools -> Sort lines, I get the error "This tool is not compatible with binary text. Please select text without [NUL] characters" regardless of which file I try it with. Even a new file with only a single character will throw the error.
> 
> I am using the x64 version.

No problem recognizable:
![image](https://github.com/rainman74/NPPTextFX2/assets/16306963/e2429850-ffc1-4901-851a-5ad6a3072dd0)

**Comment by PhilCS** [comment]
![image](https://github.com/rainman74/NPPTextFX2/assets/6107256/7d3146ff-23cb-4b53-8913-1a440c329fc1)

**Comment by rainman74** [comment]
>

Some other extension or a marko seems to insert a binary character in Notepad? This is only normal! Save your text as it is and send me the file here via drag & drop.

**Comment by PhilCS** [comment]
There were no binary characters in the file. I updated NPP from 8.3.3 to 8.6.5 and the problem is gone, sorting works.
