### ISSUE TITLE
Not binary compatible with 64-bit Notepad++

### ISSUE THREAD

**Issue by rdipardo** [rainman74/NPPTextFX2#3]
In order to support 64-bit Notepad++, this plugin's interface needs to catch up with the following milestones:

#### Notepad++ 7.7

Scintilla 4.14 added new members to the `SCNotification` structure.

- https://github.com/notepad-plus-plus/notepad-plus-plus/blob/37c4b894cc247d1ee6976bc1a1b66cfed4b7774e/scintilla/include/Scintilla.h#L1226-L1229
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5741

The plugin currently defines a `SCNotification` structure without the additional members:

https://github.com/rainman74/NPPTextFX2/blob/a9ae47c908c5eb2dda6f14038cd3566d4f724bf3/SRC/Scintilla.h#L742-L743

A few of the members it does have are of type `int`, which is too small for 64-bit editors.

#### Notepad++ 8.3

The `CharacterRange` structure was enlarged to accommodate 64-bit positions in documents >2 GiB.
This was done by re-declaring the `Sci_PositionCR` type as `intptr_t`, which matches the size of a pointer in the target instruction set: 4 bytes in 32-bit DLLs (i.e., no difference compared to older versions); 8-bytes in 64-bit ones.

- https://community.notepad-plus-plus.org/topic/22471/prevent-plugin-from-crash-on-v8-3-and-later-version-recompile-x64-plugins-with-new-header
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11198

The plugin currently defines a `CharacterRange` structure with members of type `long`:
https://github.com/rainman74/NPPTextFX2/blob/a9ae47c908c5eb2dda6f14038cd3566d4f724bf3/SRC/Scintilla.h#L684-L687

A `long` is [limited to 32 bits on all architectures of Windows][0].

[0]: https://groups.google.com/g/scintilla-interest/c/mPLwYdC0-FE#:~:text=The%20key%20Sci_CharacterRange%20struct%20uses%20%E2%80%98long%E2%80%99%20for%20positions%20which%20is%2064%2Dbit%20on%2064%2Dbit%20Unix%20systems%20but%2032%2Dbit%20on%2064%2Dbit%20Win32%20systems.
[1]: https://github.com/rainman74/NPPTextFX2#:~:text=The%2064%20bit%20version%20of%20the%20plugin%20can%20be%20compiled%2C%20but%20the%20functions%20do%20not%20work%20in%20large%20parts.

At a bare minimum, a type definition for `Sci_Position` must be added, and the interface header updated as shown:

~~~diff
diff --git a/SRC/Sci_Position.h b/SRC/Sci_Position.h
new file mode 100644
index 0000000..88ad513
--- /dev/null
+++ b/SRC/Sci_Position.h
@@ -0,0 +1,29 @@
+// Scintilla source code edit control
+/** @file Sci_Position.h
+ ** Define the Sci_Position type used in Scintilla's external interfaces.
+ ** These need to be available to clients written in C so are not in a C++ namespace.
+ **/
+// Copyright 2015 by Neil Hodgson <neilh@scintilla.org>
+// The License.txt file describes the conditions under which this software may be distributed.
+
+#ifndef SCI_POSITION_H
+#define SCI_POSITION_H
+
+#include <stddef.h>
+
+// Basic signed type used throughout interface
+typedef ptrdiff_t Sci_Position;
+
+// Unsigned variant used for ILexer::Lex and ILexer::Fold
+typedef size_t Sci_PositionU;
+
+// For Sci_CharacterRange  which is defined as long to be compatible with Win32 CHARRANGE
+typedef intptr_t Sci_PositionCR;
+
+#ifdef _WIN32
+	#define SCI_METHOD __stdcall
+#else
+	#define SCI_METHOD
+#endif
+
+#endif
diff --git a/SRC/Scintilla.h b/SRC/Scintilla.h
index 354f28d..bda1510 100644
--- a/SRC/Scintilla.h
+++ b/SRC/Scintilla.h
@@ -36,6 +36,8 @@ typedef unsigned long uptr_t;
 typedef long sptr_t;
 #endif
 
+#include "Sci_Position.h"
+
 typedef sptr_t (*SciFnDirect)(sptr_t ptr, unsigned int iMessage, uptr_t wParam, sptr_t lParam);
 
 //++Autogenerated -- start of section automatically generated from Scintilla.iface
@@ -682,8 +684,8 @@ typedef sptr_t (*SciFnDirect)(sptr_t ptr, unsigned int iMessage, uptr_t wParam,
 // So older code that treats Scintilla as a RichEdit will work.
 
 struct CharacterRange {
-	long cpMin;
-	long cpMax;
+	Sci_PositionCR cpMin;
+	Sci_PositionCR cpMax;
 };
 
 struct TextRange {
@@ -723,23 +725,27 @@ struct NotifyHeader {
 
 struct SCNotification {
 	struct NotifyHeader nmhdr;
-	int position;	// SCN_STYLENEEDED, SCN_MODIFIED, SCN_DWELLSTART, SCN_DWELLEND
+	Sci_Position position;	// SCN_STYLENEEDED, SCN_MODIFIED, SCN_DWELLSTART, SCN_DWELLEND
 	int ch;		// SCN_CHARADDED, SCN_KEY
 	int modifiers;	// SCN_KEY
 	int modificationType;	// SCN_MODIFIED
 	const char *text;	// SCN_MODIFIED, SCN_USERLISTSELECTION, SCN_AUTOCSELECTION
-	int length;		// SCN_MODIFIED
-	int linesAdded;	// SCN_MODIFIED
+	Sci_Position length;		// SCN_MODIFIED
+	Sci_Position linesAdded;	// SCN_MODIFIED
 	int message;	// SCN_MACRORECORD
 	uptr_t wParam;	// SCN_MACRORECORD
 	sptr_t lParam;	// SCN_MACRORECORD
-	int line;		// SCN_MODIFIED
+	Sci_Position line;		// SCN_MODIFIED
 	int foldLevelNow;	// SCN_MODIFIED
 	int foldLevelPrev;	// SCN_MODIFIED
 	int margin;		// SCN_MARGINCLICK
 	int listType;	// SCN_USERLISTSELECTION
 	int x;			// SCN_DWELLSTART, SCN_DWELLEND
 	int y;		// SCN_DWELLSTART, SCN_DWELLEND
+	int token;		// SCN_MODIFIED with SC_MOD_CONTAINER
+	Sci_Position annotationLinesAdded;	// SCN_MODIFIED with SC_MOD_CHANGEANNOTATION
+	int updated;	// SCN_UPDATEUI
+	int listCompletionMethod; // SCN_AUTOCSELECTION, SCN_AUTOCCOMPLETED, SCN_USERLISTSELECTION
 };
 
 // Deprecation section listing all API features that are deprecated and will
 
~~~

[0001-NPPTextFX2-update-sci-iface.diff.txt](https://github.com/rainman74/NPPTextFX2/files/9128370/0001-NPPTextFX2-update-sci-iface.diff.txt)

After these changes, 64-bit DLLs will require *at least* Notepad++ v8.3:  https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a06b4047
All builds will require *at least* Notepad++ v7.7

**Comment by rainman74** [comment]
> In order to support 64-bit Notepad++, this plugin's interface needs to catch up with the following milestones:

Thank you for your comments. Could you maybe do a PR on this?

I'm afraid I don't have the time and the x64 build wasn't my scope either and I've never dealt with NPP plugins before and would have to catch up too much.

It doesn't look like much ... ;-)

**Comment by rainman74** [comment]
> In order to support 64-bit Notepad++, this plugin's interface needs to catch up with the following milestones:
> 
> After these changes, 64-bit DLLs will require _at least_ Notepad++ v8.3: [notepad-plus-plus/notepad-plus-plus@a06b4047](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a06b4047) All builds will require _at least_ Notepad++ v7.7

So, I had some time and did this once quickly, but I have not tested the x64 build.

NPPTextFX2 v1.01 x86
NPPTextFX2 v1.01 x64
