### ISSUE TITLE
Version 0.26 of TextFX was not ported; options missing

### ISSUE THREAD

**Issue by bigd1182** [rainman74/NPPTextFX2#4]
The version of TextFX that was ported to this project appears to be 1 rev behind the last v0.2x releases. The menu is missing options...
![image](https://user-images.githubusercontent.com/20261408/184979205-877d8bb0-f6c4-48fa-8b57-11bb84c81ff1.png)

And the unwrap functions are missing from the TextFX Edit submenu...
![image](https://user-images.githubusercontent.com/20261408/184979737-bda6ccaf-333d-4c4b-9639-c8e92d756c92.png)

Is it possible to port that version or add those functions to this project?

**Comment by rainman74** [comment]
Missing functions added, NppTextFX2 v1.02

**Comment by bigd1182** [comment]
Thanks @rainman74 ! You are fast!
