### ISSUE TITLE
Find/Replace feature request

### ISSUE THREAD

**Issue by dodo67** [rainman74/NPPTextFX2#5]
Hi @rainman74,
thank you for your work, this plugin saved me after Notepad++ disabled the original obsolete TextFx plugin.
The feature offered by that plugin that I used most was the "Find/Replace" dialog (`Ctrl+r` or menu `"TextFx"  > "Text Fx Quick" > "Find/Replace"`  - See screenshot [here](https://superuser.com/a/1046168)). Do you plan to reintroduce it in a future release of NPPTextFX2?
It would be **very** useful for me.
Thank you

Carlo

**Comment by rainman74** [comment]
I have adjusted Find/Replace and it now works in both versions (x86/x64)

Release 1.2
