### ISSUE TITLE
TextFX Edit menu not available under the 64-bit version

### ISSUE THREAD

**Issue by vusd-adam** [rainman74/NPPTextFX2#7]
Switched from 32-bit to 64-bit and noticed that the "TextFX -> Edit" menu option in the 64-bit version is not there. Any plans to make that available?

Thanks for all the effort to bring TextFX back. It's a seriously great plugin.

**Comment by trueqbit** [comment]
I'm also surprised that the menu is missing in v1.2 - when I compile the plugin myself, all the menus are there, and especially the "rewrap text" function works.
Probably @rainman74 hasn't tested and approved it yet?

**Comment by rainman74** [comment]
> I'm also surprised that the menu is missing in v1.2 - when I compile the plugin myself, all the menus are there, and especially the "ReWrap Text" and "Unwrap Text" functions work. Probably @rainman74 hasn't tested and approved it yet, as mentioned in #1?

No, unfortunately I have not tested it extensively.

**Comment by rainman74** [comment]
> Switched from 32-bit to 64-bit and noticed that the "TextFX -> Edit" menu option in the 64-bit version is not there. Any plans to make that available?
> 
> Thanks for all the effort to bring TextFX back. It's a seriously great plugin.

Yes I have plans to add that, but at the moment I unfortunately don't have time.

**Comment by trueqbit** [comment]
@rainman74 I am surprised you are closing this issue. Your reason not having enough time is perfectly valid, but that doesn't mean the issue is resolved.
As I said earlier the "ReWrap Text" and "Unwrap Text" functions work, and the "Edit" functions do compile, so just needs a bit of testing.

**Comment by rainman74** [comment]
> @rainman74 I am surprised you are closing this issue. Your reason not having enough time is perfectly valid, but that doesn't mean the issue is resolved. As I said earlier the "ReWrap Text" and "Unwrap Text" functions work, and the "Edit" functions do compile, so just needs a bit of testing.

This can be seen as you say, but for me this is not an open issue that I will be fixing for the foreseeable future. It's also not a "bug", so I've closed that.

Therefore, please understand.
